[tool.briefcase]
project_name = "Calorie Counter App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/caloriecounterapp"
license = "BSD license"
author = 'Ellie Graves'
author_email = "ellieagraves@gmail.com"

[tool.briefcase.app.caloriecounterapp]
formal_name = "Calorie Counter App"
description = "Beeware application to assist athletes counting calories."
icon = "src/caloriecounterapp/resources/caloriecounterapp"
sources = ['src/caloriecounterapp']
requires = []


[tool.briefcase.app.caloriecounterapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.caloriecounterapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.caloriecounterapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.caloriecounterapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.caloriecounterapp.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
